mybatis:
  mapper-locations: classpath:mappers/*.xml #需要在对应的接口上添加@Mapper注解
  type-aliases-package: vip.hewe.data.domain
spring:
  datasource:
    url: jdbc:mysql://119.29.2.209:3306/hewe_privilege
    username: hewe
    password: Hewe_Ting_0824
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#    druid:  # 初始化大小，最小，最大
#      initialSize:  5
#      minIdle:  5
#      maxActive:  20
#      maxWait:  60000 # 配置获取连接等待超时的时间
#      timeBetweenEvictionRunsMillis:  60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
#      validationQuery:  SELECT 1 FROM t_user
#      testOnBorrow: false
#      testOnReturn: false
#      testWhileIdle:  true
